#NUTPAPAT YOUYOUNG 60070024
"""FoodGrade I"""
def function():
    """This is Show Program Number of chicken wings on all"""
    number_1 = int(input())
    number_2 = int(input())
    number_3 = int(input())
    number_4 = int(input())
    number_5 = int(input())
    number_6 = int(input())
    number_7 = int(input())
    number_8 = int(input())
    number_9 = int(input())
    number_10 = int(input())
    number_11 = int(input())
    number_12 = int(input())
    number_13 = int(input())
    number_14 = int(input())
    number_15 = int(input())
    number_16 = int(input())
    number_17 = int(input())
    number_18= int(input())
    number_19 = int(input())
    number_20= int(input())
    number_21 = int(input())
    number_22 = int(input())
    number_23 = int(input())
    number_24= int(input())
    if 50 > number_1 > 70:
        print(count(number_1))
function()
